//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pageadmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập tên người dùng")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập tên đăng nhập")]
        public string Username { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập số điện thoại")]
        public string Mobile { get; set; }
        [RegularExpression(@"[A-Za-z0-9._+-]+@[A-Za-z0-9.-]+[A-Za-z]{2,4}")]
        [Required(ErrorMessage ="Vui lòng nhập email")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập địa chỉ")]
        public string Address { get; set; }
        public string PostCode { get; set; }
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8.15}", ErrorMessage = "Mật khẩu cần ít nhất 1 chữ hoa, 1 chữ thường, 1 số ít nhất 8 kí tự và nhiều nhất 15 kí tự")]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
